
project_id = "owufofvccijykqodjnxn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.process-location]
verify_jwt = false
