// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owufofvccijykqodjnxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dWZvZnZjY2lqeWtxb2RqbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MjkzNjEsImV4cCI6MjA2MTMwNTM2MX0.k0gs0y5uvWzTMW1rmK7UzsTbCUSVkyc9je5shm_qxXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);